on:
  milestone:
    types: [closed]
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install --frozen-lockfile
  create_release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Create release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: tag-${{ github.run_id }}
      #     release_name: release ${{ github.run_id }}
      - name: get milestone number
        run: export MILESTONE_NUM=$(cat $GITHUB_EVENT_PATH | jq '.milestone.number')
      - name: get link to milestone
        run: export MILESTONE_URL=$(cat $GITHUB_EVENT_PATH | jq '.milestone.url')
      - name: parse json
        run: curl "https://api.github.com/repos/wanjuntham/github-actions-playground/issues?milestone=${MILESTONE_NUM}&state=all" | jq '.[].title' | while read i; do echo $i; done