on:
  milestone:
    types: [closed]
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install --frozen-lockfile
  create_release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release notes generator
        uses: Decathlon/release-notes-generator-action@v3.1.5
        env:
          USE_MILESTONE_TITLE: true
          OUTPUT_FOLDER: ./release_notes
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit release notes to repo
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions